from collections.abc import Sequence
from typing import TypedDict


class GameSeed(TypedDict):
    id: str
    title: str
    desc: str
    players: str
    level: str
    duration: str
    category: str
    tone: str
    is_active: bool
    order_index: int


GAMES_SEED: Sequence[GameSeed] = [
    {
        "id": "baraban-metodi",
        "title": "Baraban metodi",
        "desc": "Tasodifiy tanlov orqali sinfda faollikni oshiradigan o'yin.",
        "players": "1.2k+",
        "level": "Oddiy",
        "duration": "5 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-cyan-500 to-blue-500",
        "is_active": True,
        "order_index": 1,
    },
    {
        "id": "arqon-tortish",
        "title": "Arqon tortish o'yini",
        "desc": "Jamoaviy hamkorlik va tez qaror qilishni kuchaytiradi.",
        "players": "1.4k+",
        "level": "O'rta",
        "duration": "8 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-orange-500 to-amber-500",
        "is_active": True,
        "order_index": 2,
    },
    {
        "id": "soz-qidiruv",
        "title": "So'z qidiruv o'yini",
        "desc": "Harflar ichidan yashirilgan so'zlarni topish topshirig'i.",
        "players": "1.7k+",
        "level": "Murakkab",
        "duration": "10 daqiqa",
        "category": "Tillar",
        "tone": "from-emerald-500 to-lime-500",
        "is_active": True,
        "order_index": 3,
    },
    {
        "id": "millioner",
        "title": "Millioner viktorina",
        "desc": "2 jamoa bir xil savolda bellashadi: birinchi to'g'ri topgan ko'proq ball oladi.",
        "players": "1.1k+",
        "level": "O'rta",
        "duration": "12 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-indigo-500 to-violet-500",
        "is_active": True,
        "order_index": 4,
    },
    {
        "id": "puzzle-mozaika",
        "title": "Puzzle mozaika",
        "desc": "Rasm bo'laklarini to'g'ri joylab mantiq va diqqatni rivojlantiring.",
        "players": "1.0k+",
        "level": "O'rta",
        "duration": "7 daqiqa",
        "category": "Mantiq",
        "tone": "from-sky-500 to-indigo-500",
        "is_active": True,
        "order_index": 5,
    },
    {
        "id": "inglizcha-soz",
        "title": "Inglizcha so'z o'yini",
        "desc": "Yangi so'zlarni rasm bilan bog'lab tez yod olish usuli.",
        "players": "1.9k+",
        "level": "O'rta",
        "duration": "9 daqiqa",
        "category": "Tillar",
        "tone": "from-rose-500 to-pink-500",
        "is_active": True,
        "order_index": 6,
    },
    {
        "id": "bayroq-topish",
        "title": "Bayroq topish o'yini",
        "desc": "Bayroqni ko'rib to'g'ri davlat nomini topadigan jamoaviy viktorina.",
        "players": "1.2k+",
        "level": "O'rta",
        "duration": "8 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-cyan-500 to-blue-500",
        "is_active": True,
        "order_index": 7,
    },
    {
        "id": "tezkor-hisob",
        "title": "Tezkor hisob",
        "desc": "Qisqa vaqtda misollarni yechib hisoblash tezligini oshiring.",
        "players": "1.3k+",
        "level": "O'rta",
        "duration": "6 daqiqa",
        "category": "Matematika",
        "tone": "from-sky-500 to-indigo-500",
        "is_active": True,
        "order_index": 8,
    },
    {
        "id": "jumla-ustasi",
        "title": "Jumla ustasi",
        "desc": "Aralash so'zlarni to'g'ri tartiblab jumla hosil qiling.",
        "players": "1.1k+",
        "level": "O'rta",
        "duration": "8 daqiqa",
        "category": "Tillar",
        "tone": "from-purple-500 to-fuchsia-500",
        "is_active": True,
        "order_index": 9,
    },
    {
        "id": "ranglar-olami",
        "title": "Ranglar olami",
        "desc": "Rang va shakllarni tanish bo'yicha qiziqarli mini-topshiriq.",
        "players": "940+",
        "level": "Oddiy",
        "duration": "6 daqiqa",
        "category": "Ijodiy",
        "tone": "from-amber-500 to-orange-500",
        "is_active": True,
        "order_index": 10,
    },
    {
        "id": "xotira-zanjiri",
        "title": "Xotira zanjiri",
        "desc": "Ketma-ketlikni eslab qolish orqali e'tiborni kuchaytiring.",
        "players": "1.0k+",
        "level": "O'rta",
        "duration": "7 daqiqa",
        "category": "Mantiq",
        "tone": "from-emerald-500 to-teal-500",
        "is_active": True,
        "order_index": 11,
    },
    {
        "id": "box-jang",
        "title": "Math Box jang",
        "desc": "Kim tez va to'g'ri topsa, o'sha birinchi zarba beradigan matematik duel.",
        "players": "1.0k+",
        "level": "O'rta",
        "duration": "8 daqiqa",
        "category": "Matematika",
        "tone": "from-cyan-500 to-blue-500",
        "is_active": True,
        "order_index": 12,
    },
    {
        "id": "car-racing-math",
        "title": "Car Racing Math",
        "desc": "Misolni kim tez va to'g'ri topsa, o'sha mashinasi oldinga yuradigan poyga.",
        "players": "920+",
        "level": "O'rta",
        "duration": "9 daqiqa",
        "category": "Matematika",
        "tone": "from-sky-500 to-blue-600",
        "is_active": True,
        "order_index": 13,
    },
    {
        "id": "jumanji",
        "title": "Jumanji board quest",
        "desc": "Savolga javob berib zar tashlang va 30 qadamli taxtada finishga birinchi yeting.",
        "players": "860+",
        "level": "O'rta",
        "duration": "10 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-emerald-600 to-amber-600",
        "is_active": True,
        "order_index": 14,
    },
    {
        "id": "quiz-battle",
        "title": "Quiz Battle",
        "desc": "Bamboozle uslubida 2-3 jamoali viktorina: kartalar, random eventlar va jonli scoreboard.",
        "players": "1.5k+",
        "level": "O'rta",
        "duration": "10 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-cyan-500 to-indigo-500",
        "is_active": True,
        "order_index": 15,
    },
    {
        "id": "one-question-100-answers",
        "title": "1 Savol - 100 Javob",
        "desc": "Battle Royale Team Edition: 50+ o'yinchi, ko'p javobli savollar, unique scoring va elimination.",
        "players": "2.2k+",
        "level": "Murakkab",
        "duration": "15 daqiqa",
        "category": "Jamoaviy",
        "tone": "from-cyan-500 via-sky-500 to-fuchsia-500",
        "is_active": True,
        "order_index": 16,
    },
    {
        "id": "fake-or-fact-pro",
        "title": "FAKE or FACT PRO",
        "desc": "FAKT yoki FEYKni topishga asoslangan premium mediasavod va mantiq bellashuvi.",
        "players": "2 jamoa",
        "level": "O'rta",
        "duration": "10 daqiqa",
        "category": "Mantiq",
        "tone": "from-cyan-500 via-sky-500 to-fuchsia-500",
        "is_active": True,
        "order_index": 17,
    },
    {
        "id": "topqirlik-kvest",
        "title": "Topqirlik kvesti",
        "desc": "Ketma-ket jumboqlar bilan kichik sarguzasht rejimi.",
        "players": "870+",
        "level": "Murakkab",
        "duration": "12 daqiqa",
        "category": "Ijodiy",
        "tone": "from-fuchsia-500 to-indigo-500",
        "is_active": True,
        "order_index": 18,
    },
]
